---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      # - docker
      # - google-chrome
      # - iterm2
      # - visual-studio-code
      - slack
      - zoom
    brew_packages:
      # - autoconf
      # - bash-completion
      # - boot2docker
      # - consul
      # - docker-compose
      # - docker-machine
      # - doxygen
      # - git
      # - git-lfs
      # - go
      - jq
      # - nmap
      # - nomad
      # - openssl
      # - packer
      - pyenv
      # - python
      # - ssh-copy-id
      # - terraform
      # - terraform-inventory
      # - terraform-provisioner-ansible
      - tmux
      - tree
      - fzf
      - wget
      - btop
      - tldr
      # - zsh
      # - zsh-syntax-highlighting
    install_homebrew_if_missing: false
    python_modules:
    #   - configparser
      - pylint
    #   - virtualenv
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Check and Install Homebrew Cask Packages
      block:
        - name: Check if Homebrew Cask package is installed
          command: brew list --cask "{{ item }}"
          register: cask_check
          failed_when: false
          changed_when: false
          with_items: "{{ brew_cask_packages }}"

        - name: Install Homebrew Cask packages
          homebrew_cask:
            name: "{{ item }}"
            state: present
          with_items: "{{ brew_cask_packages }}"
          when: item not in cask_check.results | map(attribute='stdout') | join(' ')

    - name: Check and Install Homebrew Packages
      block:
        - name: Check if Homebrew package is installed
          command: brew list "{{ item }}"
          register: brew_check
          failed_when: false
          changed_when: false
          with_items: "{{ brew_packages }}"

        - name: Install Homebrew packages
          homebrew:
            name: "{{ item }}"
            state: present
          with_items: "{{ brew_packages }}"
          when: item not in brew_check.results | map(attribute='stdout') | join(' ')

    - name: Check and Install Python Modules
      block:
        - name: Check if Python module is installed
          pip:
            name: "{{ item }}"
            state: present
          register: python_check
          failed_when: false
          changed_when: false
          with_items: "{{ python_modules }}"

        - name: Install Python modules
          pip:
            name: "{{ item }}"
            state: present
          with_items: "{{ python_modules }}"
          when: item not in python_check.results | map(attribute='name') | join(' ')