- hosts: localhost
  tasks:
  - name: Install NVM
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

  - name: Load NVM and install Node.js
    ansible.builtin.shell: >
      source {{ ansible_env.HOME }}/.nvm/nvm.sh &&
      nvm install --lts &&
      nvm install --latest-npm &&
      nvm alias default 'lts/*'
      # nvm use v21.7.2
      # nvm alias default v21.7.2
    args:
      executable: /bin/bash  # Ensure the command runs in a bash shell
    environment:
      NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    when: ansible_env.NVM_DIR is not defined or ansible_env.NVM_DIR == ""

  - name: Verify Node.js installation
    ansible.builtin.shell: >
      source {{ ansible_env.HOME }}/.nvm/nvm.sh &&
      node -v
    args:
      executable: /bin/bash

  - name: Install Yarn
    ansible.builtin.shell: >
      source {{ ansible_env.HOME }}/.nvm/nvm.sh &&
      npm install --global yarn
    args:
      executable: /bin/bash
    environment:
      NVM_DIR: "{{ ansible_env.HOME }}/.nvm"

  - name: Verify Yarn installation
    ansible.builtin.shell: >
      yarn --version
    args:
      executable: /bin/bash
